name: tfgrid-nextcloud
version: "1.0.0"
description: Nextcloud All-in-One cloud platform

patterns:
  recommended: single-vm
  supported:
    - single-vm

resources:
  cpu:
    min: 2
    recommended: 4
  memory:
    min: 4096
    recommended: 8192
  disk:
    min: 50
    recommended: 200
  ports:
    - 22:ssh
    - 80:http
    - 443:https
    - 8080:aio-interface
    - 8443:aio-interface-https

hooks:
  setup: deployment/setup.sh
  configure: deployment/configure.sh
  healthcheck: deployment/healthcheck.sh

environment:
  # Domain Configuration
  - name: DOMAIN
    required: true
    description: "Public domain for Nextcloud (e.g., cloud.example.com)"
    
  # DNS Automation (name.com, cloudflare, godaddy recommended for full automation)
  - name: DNS_PROVIDER
    required: false
    description: "DNS provider for automatic A record setup"
    options:
      - manual
      - name.com
      - cloudflare
      - godaddy
      - namecheap  # Requires manual IP whitelisting in Namecheap dashboard
    default: "manual"
  - name: NAMECOM_USERNAME
    required: false
    description: "Name.com username"
    depends_on:
      DNS_PROVIDER: "name.com"
  - name: NAMECOM_API_TOKEN
    required: false
    secret: true
    description: "Name.com API token"
    depends_on:
      DNS_PROVIDER: "name.com"
  - name: CLOUDFLARE_API_TOKEN
    required: false
    secret: true
    description: "Cloudflare API token"
    depends_on:
      DNS_PROVIDER: "cloudflare"
  - name: GODADDY_API_KEY
    required: false
    description: "GoDaddy API key"
    depends_on:
      DNS_PROVIDER: "godaddy"
  - name: GODADDY_API_SECRET
    required: false
    secret: true
    description: "GoDaddy API secret"
    depends_on:
      DNS_PROVIDER: "godaddy"
  - name: NAMECHEAP_API_USER
    required: false
    description: "Namecheap API username (requires IP whitelisting - not fully automated)"
    depends_on:
      DNS_PROVIDER: "namecheap"
  - name: NAMECHEAP_API_KEY
    required: false
    secret: true
    description: "Namecheap API key (requires IP whitelisting - not fully automated)"
    depends_on:
      DNS_PROVIDER: "namecheap"
      
  # Nextcloud Settings
  - name: NEXTCLOUD_ADMIN_USER
    required: false
    description: "Nextcloud admin username"
    default: "admin"
  - name: NEXTCLOUD_ADMIN_PASSWORD
    required: false
    secret: true
    description: "Nextcloud admin password (auto-generated if not set)"
  - name: NEXTCLOUD_DATADIR
    required: false
    description: "Data directory path"
    default: "/mnt/ncdata"
  - name: NEXTCLOUD_UPLOAD_LIMIT
    required: false
    description: "Maximum upload file size"
    default: "10G"
  - name: NEXTCLOUD_MEMORY_LIMIT
    required: false
    description: "PHP memory limit"
    default: "512M"
    
  # Optional Features
  - name: COLLABORA_ENABLED
    required: false
    description: "Enable Collabora Online Office"
    default: "false"
  - name: TALK_ENABLED
    required: false
    description: "Enable Nextcloud Talk video calls"
    default: "false"
  - name: ONLYOFFICE_ENABLED
    required: false
    description: "Enable OnlyOffice (alternative to Collabora)"
    default: "false"
    
  # Backup Configuration
  - name: BACKUP_LOCATION
    required: false
    description: "Backup storage location"
    default: "/mnt/backup"
  - name: BACKUP_RETENTION
    required: false
    description: "Number of backups to keep"
    default: "7"

commands:
  backup:
    script: /opt/nextcloud/scripts/backup.sh
    description: "Trigger AIO backup (uses built-in BorgBackup)"
  backup-status:
    script: /opt/nextcloud/scripts/backup-status.sh
    description: "Check backup status and list backups"
  restore:
    script: /opt/nextcloud/scripts/restore.sh
    description: "Show restore instructions"
  logs:
    script: /opt/nextcloud/scripts/logs.sh
    description: "View Nextcloud logs"
    args: "[mastercontainer|nextcloud|database|redis|apache] [--follow]"
  update:
    script: /opt/nextcloud/scripts/update.sh
    description: "Check for and apply updates"
  occ:
    script: /opt/nextcloud/scripts/occ.sh
    description: "Run Nextcloud occ commands"
    args: "<occ-command>"
  restart:
    script: /opt/nextcloud/scripts/restart.sh
    description: "Restart Nextcloud services"

status:
  check_interval: 60
  endpoints:
    - path: /status.php
      expected_status: 200

logging:
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

tags:
  - nextcloud
  - cloud
  - storage
  - collaboration
  - docker
  - file-sync
